#tính năm âm lịch
def tinh_can(nam):
      if nam%10 == 0:
            return 'Canh'
      elif nam%10==1:
            return 'Tân'
      elif nam%10==2:
            return 'Nhâm'
      elif nam%10==3:          
            return 'Quý'
      elif nam%10==4: 
            return 'Giáp'
      elif nam%10==5:
            return 'Ất'
      elif nam%10==6:
            return 'Bính'
      elif nam%10==7:
            return 'Đinh'
      elif nam%10==8:
            return 'Mậu'
      else:
            return 'Kỷ'
def tinh_chi(nam):
      if nam%12==0:
            return 'Thân'
      if nam%12==1:
            return 'Dậu'
      if nam%12==2:
            return 'Tuất'
      if nam%12==3:
            return 'Hợi'
      if nam%12==4:
            return 'Tý'
      if nam%12==5:
            return 'Sửu'
      if nam%12==6:
            return 'Dần'
      if nam%12==7:
            return 'Mão'
      if nam%12==8:
            return 'Thìn'
      if nam%12==9:
            return 'Tỵ'
      if nam%12==10:
            return 'Ngọ'
      else:
            return 'Mùi'
x=int(input('Nhập năm:'))
print('Năm',x,'là năm:',tinh_can(x),tinh_chi(x))